@host = https://localhost:1337/v2
# 1337 is gateway, 1338 is software api, 1339 is vendors api.
### Adding a Vendor

POST {{host}}/vendors HTTP/1.1
Host: software-api
Content-Type: application/json

{"name":"Enzi","url":"https://www.Hypertheory.com",
"pointOfContact":{"name":"Jeff","email":"jeff@hypertheory","phone":"867-5309"}}


### Change Point of Contact

PUT {{host}}/vendors/bcda1cd9-09fb-44dd-bd92-ace8de8d51b0/point-of-contact HTTP/1.1
Host: software-api
Content-Type: application/json

{"name":"adam","email":"satya@microsoft.com","phone":"555-1212"}


### GET all vendors

GET https://localhost:1337/v2/vendors


### Get individual vendor

GET {{host}}/vendors/55e7d4ba-e1bf-4572-b675-0215042d44dc


### Delete

DELETE {{host}}/vendors/bdfb1739-43c8-4cf8-a278-61c06aff70bb